version: "2.0"
services:
    iot:
        container_name: web_iot
        build:
            context: . # dockerfile location
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - .:/var/www/html/ 
        ports:
            - 2390:80
    db:
        container_name: db_iot
        image: mariadb
        restart: always
        volumes:
            - ./vicount_db.sql:/docker-entrypoint-initdb.d/vicount_db.sql:rw
        environment:
            MYSQL_ROOT_PASSWORD: thispassword

        ports:
            - "8000:3306"

    phpmyadmin:
        container_name: phpmyadmin_iot
        image: phpmyadmin
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_ARBITARY=1

